FROM jallytom/erlang

# setup powershell options for RUN commands
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

EXPOSE 5672 15672

# download and install erlang using silent install option, and remove installer when done
# download and extract rabbitmq, and remove zip file when done
# remove version from rabbitmq folder name
RUN scoop install rabbitmq

VOLUME C:\\Users\\ContainerAdministrator\\appdata\\Roaming\\RabbitMQ\\db

# enable managment plugin
RUN c:\Users\ContainerAdministrator\scoop\apps\rabbitmq\current\sbin\rabbitmq-plugins.bat enable rabbitmq_management --offline

# create config file
RUN ["cmd", "/C", "echo [{rabbit, [{loopback_users, []}]}].> C:\\Users\\ContainerAdministrator\\AppData\\Roaming\\RabbitMQ\\rabbitmq.config"]

# run server when container starts - container will shutdown when this process ends
CMD c:\Users\ContainerAdministrator\scoop\apps\rabbitmq\current\sbin\rabbitmq-server.bat

#docker create --restart always -v D:\data\docker\rabbitmq\db:C:\Users\ContainerAdministrator\appdata\Roaming\RabbitMQ\db --name rabbitmq --restart=always -p 15672:15672 -p 5672:5672 jallytom/rabbitmq
#docker create --restart always --name rabbitmq --restart=always -p 15672:15672 -p 5672:5672 jallytom/rabbitmq