FROM jallytom/erlang

####### PORTS ########
#Main rabbitmq port
EXPOSE 5672

#rabbitmq management console
EXPOSE 15672

#install rabbitmq
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN scoop install rabbitmq	

#RUN ["cmd", "/C", "echo [{rabbit, [{loopback_users, []}]}].> C:\\Users\\ContainerAdministrator\\appdata\\Roaming\\RabbitMQ\\rabbitmq.config"]

RUN rabbitmq-plugins enable rabbitmq_management --offline
#set up the path to the config file
VOLUME C:\\Users\\ContainerAdministrator\\appdata\\Roaming\\RabbitMQ

#set the startup command to be rabbit
CMD ["C:/Users/ContainerAdministrator/scoop/apps/rabbitmq/current/sbin/rabbitmq-server.bat"]

#docker create --restart always -v D:\data\docker\rabbitmq\data:C:\Users\ContainerAdministrator\appdata\Roaming\RabbitMQ --name rabbitmq --restart=always -p 15672:15672 -p 5672:5672 jallytom/rabbitmq
#docker create --restart always --name rabbitmq --restart=always -p 15672:15672 -p 5672:5672 jallytom/rabbitmq