FROM jallytom/scoop

# setup powershell options for RUN commands
RUN powershell -Command \
    $ErrorActionPreference = 'Stop'; \
    scoop install erlang ; \
    scoop install rabbitmq ; \
    c:\Users\ContainerAdministrator\scoop\apps\rabbitmq\current\sbin\rabbitmq-plugins.bat enable rabbitmq_management --offline 
	
RUN echo [{rabbit, [{loopback_users, []}]}].> C:\Users\ContainerAdministrator\AppData\Roaming\RabbitMQ\rabbitmq.config
	
EXPOSE 5672 15672

VOLUME C:\\Users\\ContainerAdministrator\\appdata\\Roaming\\RabbitMQ\\db

CMD c:\Users\ContainerAdministrator\scoop\apps\rabbitmq\current\sbin\rabbitmq-server.bat

#docker create --restart always -v D:\data\docker\rabbitmq\db:C:\Users\ContainerAdministrator\appdata\Roaming\RabbitMQ\db --name rabbitmq --restart=always -p 15672:15672 -p 5672:5672 jallytom/rabbitmq
