FROM mcr.microsoft.com/windows/servercore:ltsc2019

EXPOSE 1433

# setup powershell options for RUN commands
ENV sa_password="_" \    
    ACCEPT_EULA="_" \
    sa_password_path="C:\ProgramData\Docker\secrets\sa-password"

COPY SQLServer2019 /sqlserver
COPY ConfigurationFile.ini /sqlserver
COPY start.ps1 /
WORKDIR /
VOLUME c:\\data

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN c:\sqlserver\setup.exe /CONFIGURATIONFILE="c:\sqlserver\ConfigurationFile.ini" ; \
	CMD /s "rd /s/q c:\sqlserver" ; \
    stop-service MSSQLSERVER ; \
    set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpdynamicports -value '' ; \
    set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpport -value 1433 ; \
    set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\' -name LoginMode -value 2 

HEALTHCHECK CMD [ "sqlcmd", "-Q", "select 1" ]
CMD .\start -sa_password $env:sa_password -ACCEPT_EULA $env:ACCEPT_EULA

#docker create --name sqlserver --restart always -p 1433:1433 -e sa_password=forget!800622 -e ACCEPT_EULA=Y -v d:\data\docker\sqlserver:c:\data jt/sqlserver


