FROM mcr.microsoft.com/windows/servercore:ltsc2019

RUN powershell -Command \
	$ErrorActionPreference = 'Stop'; \
	Invoke-WebRequest -Method Get -Uri http://nginx.org/download/nginx-1.17.7.zip -OutFile c:\nginx.zip ; \
	Expand-Archive -Path c:\nginx.zip -DestinationPath c:\ ; \
	Remove-Item c:\nginx.zip -Force 
#	Remove-Item C:\nginx\conf\* -Force

WORKDIR /nginx-1.17.7

VOLUME C:\\nginx-1.17.7\\conf
CMD c:/nginx-1.17.7/nginx.exe


#docker create --name nginx -v D:\data\docker\nginx:C:\nginx-1.17.7\conf --restart always -p 80:80 jt/nginx